spring.datasource.url=jdbc:postgresql://localhost:5432/inkmapdb
spring.datasource.username=inkmapuser
spring.datasource.password=inkmappassword
spring.datasource.driver-class-name=org.postgresql.Driver

google.client.id=YOUR_GOOGLE_CLIENT_ID

jwt.secret=YOUR_LONG_JWT_SECRET_MIN_32_CHARS

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@ucenfotec.ac.cr
spring.mail.password=YOUR_GOOGLE_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

groq.api.key=YOUR_GROQ_API_KEY
groq.model=llama-3.3-70b-versatile
groq.whisper.model=whisper-large-v3-turbo
