spring.datasource.url=jdbc:postgresql://localhost:5432/inkmap-db
spring.datasource.username=inkmapuser
spring.datasource.password=inkmappassword
spring.datasource.driver-class-name=org.postgresql.Driver

google.client.id=YOUR_GOOGLE_CLIENT_ID
jwt.secret=YOUR_LONG_JWT_SECRETLJWT_SECRET